#!/usr/bin/env python3
# coding=utf-8

import argparse
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

sys.path.append(os.path.join(SRC_ROOT, "infra_build", "config"))
sys.path.append(os.path.join(SRC_ROOT, "infra_build", "script"))

from enviroment import TargetEnvironment, all_target  # pylint: disable=wrong-import-position


def _as_cmake_value(value):
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, list):
        return ";".join(str(item) for item in value)
    return "" if value is None else str(value)


def _escape_cmake(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _write_json(path, payload):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as file:
        json.dump(payload, file, indent=2, ensure_ascii=False)


def _write_cmake(path, payload):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as file:
        file.write("# Auto-generated by export_target_env.py\n")
        for key, value in payload.items():
            file.write(f'set({key} "{_escape_cmake(_as_cmake_value(value))}")\n')


def main():
    parser = argparse.ArgumentParser(description="Export target environment for CMake consumption")
    parser.add_argument("--target", required=True, help="Target name, e.g. ws63-liteos-app")
    parser.add_argument("--extra-defines", nargs="*", default=[], help="Extra defines")
    parser.add_argument("--json-out", required=True, help="Output json file")
    parser.add_argument("--cmake-out", required=True, help="Output cmake include file")
    parser.add_argument("--output-root", default=os.path.join(SRC_ROOT, "output"), help="Build output root")
    args = parser.parse_args()

    if args.target not in all_target:
        print(f"ERROR: invalid target '{args.target}'")
        return 1

    target_env = TargetEnvironment(args.target, args.extra_defines)

    payload = {
        "SCHEMA": "fbb.target.env/v1",
        "TARGET": args.target,
        "BUILD_TARGET_NAME": args.target.replace("-", "_"),
        "PKG_TARGET_NAME": args.target,
        "ROOT_DIR": SRC_ROOT,
        "OUTPUT_ROOT": os.path.abspath(args.output_root),
        "SDK_OUTPUT_PATH": os.path.abspath(os.path.join(args.output_root, "sdk")),
        "PY_PATH": sys.executable,
        "NHSO": False,
        "BUILD_LEVEL": "normal"
    }

    for key, value in target_env.config.items():
        payload[key.upper()] = value

    payload["CMAKE_TOOLCHAIN_FILE"] = target_env.get_tool_chain()

    _write_json(args.json_out, payload)
    _write_cmake(args.cmake_out, payload)

    print(f"Exported target env for {args.target}")
    print(f"  json:  {args.json_out}")
    print(f"  cmake: {args.cmake_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
